### ISSUE TITLE
Idea: could you fund your project with an affiliate link to Backblaze?

### ISSUE THREAD

**Issue by OhioVR** [KonstantinSchubert/zero#7]
Hello,

I was thinking that you could offer a way to fund your project by encouraging users to follow an affiliate link that goes to a Backblaze order page. I don't know for sure but I would think this is a legitimate affiliate scheme but you would need to check with Backblaze to be sure. I am not currently a Backblaze user but I would happily give this software a go along with following an affiliate link since it costs me nothing to do so and could help you out. Might not be a lot of money at this time but who knows. I think this project has a huge amount of potential and this method of raising money seems like a low hanging fruit..

-OhioVR

**Comment by KonstantinSchubert** [comment]
Hi, 

that's a very good idea and very kind of you to open an issue to bring it up.
I will actually leave that issue open until I have explored that possibility.
Thanks
Konstantin

**Comment by KonstantinSchubert** [comment]
@OhioVR Unfortunately it says on their website: 
"Also please note that affiliate commissions are only earned on Backblaze Personal and Business Backup and are not earned on B2 sales."
So, it doesn't seem like this would work.
